# Generated by Django 3.2 on 2021-05-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('adoption_url', models.CharField(max_length=300)),
                ('breed_primary', models.CharField(max_length=100)),
                ('breed_secondary', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('potcode', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('spayed_neutered', models.BooleanField()),
                ('house_trained', models.BooleanField()),
                ('special_needs', models.BooleanField()),
                ('shots_current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
