# Generated by Django 3.2 on 2021-05-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoption',
            old_name='potcode',
            new_name='postcode',
        ),
    ]
