# Generated by Django 3.2 on 2021-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_auto_20210504_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleBreeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=200)),
            ],
        ),
    ]
