# Generated by Django 3.2 on 2021-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
